apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonos-aplicados-service-deployment
  labels:
    app: bonos-aplicados-service-deployment
spec:
  selector:
    matchLabels:
      app: bonos-aplicados-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: bonos-aplicados-service-deployment
    spec:
      containers:
        - name: bonos-aplicados-service
          image: dddavidesc/bonos-aplicados-service
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_IRB
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_IRB
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_BONOS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: SECRET_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: SECRET_DB_PASSWORD
