apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ms-service-deployment
  labels:
    app: frontend-ms-service-deployment
spec:
  selector:
    matchLabels:
      app: frontend-ms-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-ms-service-deployment
    spec:
      containers:
        - name: frontend-ms-service
          image: dddavidesc/frontend-ms:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ms-service-service
  labels:
    app: frontend-ms-service-service
spec:
  selector:
    app: frontend-ms-service-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: LoadBalancer