apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_VEHICULO: cG9zdGdyZXM=
  DB_PASSWORD_VEHICULO: cGFzc3dvcmQ=
  SECRET_DB_USER: cG9zdGdyZXM=
  SECRET_DB_PASSWORD: cGFzc3dvcmQ=
 